# Generated by Django 4.2.2 on 2023-08-06 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('objetivos', models.TextField()),
                ('aportesTeoricos', models.TextField()),
                ('objetivosEspecificos', models.TextField()),
                ('descripcionProducto', models.TextField()),
                ('prerequisitos', models.TextField()),
                ('periodo', models.CharField(max_length=250)),
                ('metodosEnsenanza', models.TextField()),
                ('medios', models.TextField()),
                ('evaluacion', models.TextField()),
                ('estado', models.CharField(default='A', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('usuario', models.CharField(max_length=150, unique=True)),
                ('clave', models.CharField(max_length=150)),
                ('perfil', models.CharField(max_length=150)),
                ('estado', models.CharField(default='A', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('objetivo', models.TextField()),
                ('estado', models.CharField(default='A', max_length=3)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedimiento.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=800)),
                ('estado', models.CharField(default='A', max_length=3)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedimiento.asignatura')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedimiento.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('Biblioteca', models.BooleanField()),
                ('numerosEjemplares', models.IntegerField()),
                ('tipo', models.CharField(max_length=250)),
                ('estado', models.CharField(default='A', max_length=3)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedimiento.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.TextField()),
                ('producto_parcial', models.TextField()),
                ('resultado_estandares', models.TextField()),
                ('integracion_carreras', models.TextField()),
                ('estado', models.CharField(default='A', max_length=3)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedimiento.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('contenido', models.CharField(max_length=500)),
                ('horas_docencia', models.IntegerField()),
                ('minutos_practica', models.IntegerField()),
                ('horas_gestion', models.IntegerField()),
                ('horas_autonomas', models.IntegerField()),
                ('estado', models.CharField(default='A', max_length=3)),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedimiento.unidad')),
            ],
        ),
    ]
